mod 'aco-oracle_java', '2.9.4'
mod 'bstopp/aem', '3.0.0'
mod 'puppet-healthcheck', '0.4.1'
mod 'puppetlabs/apache', '2.3.0'
mod 'puppetlabs/concat', '4.1.0'
mod 'puppetlabs/java_ks', '1.6.0'
mod 'puppetlabs/stdlib', '4.25.1'
mod 'shinesolutions/aem_resources', '5.3.0'
