mod 'aco-oracle_java', '2.9.1'
mod 'bstopp/aem', '2.5.0'
mod 'puppet-collectd', '5.3.0'
mod 'puppetlabs/apache', '2.3.0'
mod 'puppetlabs/concat', '4.1.0'
mod 'puppetlabs/java_ks', '1.6.0'
mod 'shinesolutions/aem_resources', '2.0.0'
