mod 'aco-oracle_java', '2.8.3'
mod 'bstopp/aem', '2.5.0'
mod 'puppet-healthcheck', '0.4.0'
mod 'puppetlabs/apache', '2.3.0'
mod 'puppetlabs/concat', '4.1.0'
mod 'puppetlabs/java_ks', '1.6.0'
mod 'puppetlabs/stdlib', '4.21.0'
mod 'shinesolutions/aem_resources', '2.1.1'
