---
name: Release Patch
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - shell: bash
        run: |
          ls -all
          sed -i 's|main|feature/troubleshoot-workflow-permissions|g' .github/workflows/publish-workflow.yaml
          git config --local user.email "matthew.dingle@shinesolutions.com"
          git config --local user.name "mattd-shine"          
          git diff
          git commit -a -m "Updating workflow file"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
