---
name: Release Patch
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - shell: bash
        run: |
          sed -i 's/main/feature\/troubleshoot-workflow-permissions/g' .github/workflows/publish-workflow.yaml
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
